# Generated by Django 5.2.3 on 2025-06-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing_app', '0002_journalentry_related_affirmations_and_more'),
        ('wellbeing_app', '0003_add_affirmations'),
    ]

    operations = [
    ]
