# Generated by Django 5.2.3 on 2025-06-24 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing_app', '0004_merge_20250624_0733'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affirmation',
            name='is_user_generated',
            field=models.BooleanField(default=False, verbose_name='user generated'),
        ),
    ]
