# Generated by Django 5.2.3 on 2025-06-24 04:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing_app', '0005_affirmation_created_by_affirmation_is_user_generated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteaffirmation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite Affirmation', 'verbose_name_plural': 'Favorite Affirmations'},
        ),
        migrations.RemoveField(
            model_name='favoriteaffirmation',
            name='saved_at',
        ),
        migrations.AddField(
            model_name='affirmation',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_affirmations', through='wellbeing_app.FavoriteAffirmation', to=settings.AUTH_USER_MODEL, verbose_name='favorited by'),
        ),
        migrations.AddField(
            model_name='favoriteaffirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='favorited at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affirmations', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='affirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='wellbeing_app.affirmation', verbose_name='affirmation'),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='notes',
            field=models.TextField(blank=True, help_text='Add personal notes about why this affirmation is meaningful to you', null=True, verbose_name='personal notes'),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affirmation_favorites', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='related_affirmations',
            field=models.ManyToManyField(blank=True, help_text='Affirmations that might relate to this journal entry', related_name='journal_entries', to='wellbeing_app.affirmation', verbose_name='related affirmations'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='affirmation',
            index=models.Index(fields=['language', 'active'], name='wellbeing_a_languag_d43cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='affirmation',
            index=models.Index(fields=['created_by', 'is_user_generated'], name='wellbeing_a_created_947fcd_idx'),
        ),
    ]
