# Generated by Django 5.2.3 on 2025-06-24 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing_app', '0006_alter_favoriteaffirmation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affirmation',
            options={'ordering': ['language', 'category']},
        ),
        migrations.AlterModelOptions(
            name='favoriteaffirmation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='affirmation',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='favoriteaffirmation',
            name='notes',
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='category',
            field=models.CharField(choices=[('self_esteem', 'Self-Esteem'), ('strength', 'Strength'), ('culture', 'Cultural Identity'), ('community', 'Community')], default='self_esteem', max_length=20),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='is_user_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('mi', 'Māori')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='affirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='wellbeing_app.affirmation'),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affirmation_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
