# Generated by Django 5.2.3 on 2025-06-26 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing_app', '0007_alter_affirmation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affirmation',
            options={'ordering': ['language', 'category'], 'verbose_name': 'Affirmation', 'verbose_name_plural': 'Affirmations'},
        ),
        migrations.AlterModelOptions(
            name='favoriteaffirmation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite Affirmation', 'verbose_name_plural': 'Favorite Affirmations'},
        ),
        migrations.AddField(
            model_name='affirmation',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_affirmations', through='wellbeing_app.FavoriteAffirmation', to=settings.AUTH_USER_MODEL, verbose_name='favorited by'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='category',
            field=models.CharField(choices=[('self_esteem', 'Self-Esteem'), ('strength', 'Strength'), ('culture', 'Cultural Identity'), ('community', 'Community')], default='self_esteem', max_length=20, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affirmations', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='is_user_generated',
            field=models.BooleanField(default=False, verbose_name='user generated'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('mi', 'Māori')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='text',
            field=models.CharField(max_length=200, verbose_name='affirmation text'),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='affirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='wellbeing_app.affirmation', verbose_name='affirmation'),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='favoriteaffirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affirmation_favorites', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
