# Generated by Django 5.2.3 on 2025-07-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing_app', '0008_alter_affirmation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='content',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='related_affirmations',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='description',
            field=models.TextField(blank=True, help_text='Write your thoughts and feelings', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image to accompany your journal entry', null=True, upload_to='journal_entries/%Y/%m/%d/', verbose_name='image'),
        ),
    ]
