# Generated by Django 5.2.3 on 2025-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing_app', '0009_remove_journalentry_content_remove_journalentry_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
